version: "3.9"
services:
  
  web:
    build: .
    volumes:
    - .:/code
    ports: 
    - "${app_port}:${app_port}"
    env_file: .env
    depends_on:
      - redis
      - postgres
  
  redis:
    image: redis
    volumes:
    - .:/data
    ports:
    - "${REDIS_PORT}:${REDIS_PORT}"
    
  postgres:
    image: postgres:15
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  
  test_db:
    image: postgres:15
    container_name: ${TEST_HOST}
    volumes:
      - test_db-data:/var/lib/postgresql/data/
    ports:
      - "${TEST_PORT}:${POSTGRES_PORT}"
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=${TEST_HOST}
      - POSTGRES_DB=${TEST_DB}
      - POSTGRES_USER=${TEST_USER}
      - POSTGRES_PASSWORD=${TEST_PASSWORD}
    

volumes:
  postgres-data:
  redis:
  test_db-data: