version: "3.9"
services:
  web:
    build: .
    volumes:
    - .:/code
    ports: 
    - "${app_port}:${app_port}"
    env_file: .env
    depends_on:
      - redis
      - postgres
  redis:
    image: redis
    ports:
    - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
    - .:/data
  postgres:
    image: postgres:15
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data/

volumes:
  postgres-data:
  redis: